name: "Configure AWS"
description: "Log into AWS using a GitHub IAM role."
inputs:
  role-to-assume:
    description: "What role to assume"
    required: true
  aws-region:
    description: "What region to use"
    required: true
    default: "us-east-1"
  with-ecr:
    description: "Whether to configure ECR"
    required: false
    default: "false"
  image-registry:
    description: "ECR registry to log into"
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@49f33fe638c0cba4fb16037a27915a7ab7740259 # v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to ECR
      if: ${{ inputs.with-ecr == 'true' }}
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        registry: ${{ inputs.image-registry }}
